name: Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: "24"
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Login to Azure
        uses: azure/login@v3
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - name: Login to ACR
        run: az acr login --name ${{ secrets.ACR_NAME }}

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ secrets.ACR_NAME }}.azurecr.io/cicd-study:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push \
            ${{ secrets.ACR_NAME }}.azurecr.io/cicd-study:${{ github.sha }}